apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: productcatalogue
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: productcatalogue
  targetCPUUtilizationPercentage: 50
status:
  currentReplicas: 0
  desiredReplicas: 0
